# example client configuration for calling out to other services
# TODO: Remove / replace this configuration
example-api:
  url: "http://localhost:8080"
  client:
    id: "example-api-client"
    secret: "example-api-client-secret"

spring:
  flyway:
     locations: classpath:db/migration/dev

hmpps:
  auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    timeout: 10s
  manage-users:
    api:
      url: https://manage-users-api-dev.hmpps.service.justice.gov.uk
      timeout: 10s
  prisoner-search:
    api:
      url: https://prisoner-search-dev.prison.service.justice.gov.uk
      timeout: 10s
  sqs:
    provider: localstack
    localstackUrl: http://localhost:4566
    region: eu-west-2
    queues:
      domaineventsqueue:
        queueName: domainevents-queue
        dlqName: domainevents-queue-dlq
        subscribeTopicId: domainevents
    topics:
      domainevents:
        arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic
