#hmpps-auth:
 # url: "http://localhost:8090/auth"

# example client configuration for calling out to other services
# TODO: Remove / replace this configuration
example-api:
  url: "http://localhost:8080"
  client:
    id: "example-api-client"
    secret: "example-api-client-secret"

hmpps:
  auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${hmpps.auth.base-url}/.well-known/jwks.json

      # TODO: This client section can be removed if your service doesn't call out to other services
      client:
        provider:
          hmpps-auth:
            token-uri: ${hmpps.auth.base-url}/oauth/token

        registration:
          # example client registration for calling out to other services
          # TODO: Remove / replace this registration
          example-api:
            provider: hmpps-auth
            client-id: ${example-api.client.id}
            client-secret: ${example-api.client.secret}
            authorization-grant-type: client_credentials
            scope: read
