package uk.gov.justice.digital.hmpps.hmppsmanageprisonvisitsorchestration.dto.prisoner.search

import io.swagger.v3.oas.annotations.media.Schema
import java.time.LocalDate

data class PrisonerDto(

  @Schema(required = true, description = "Prisoner Number", example = "A1234AA")
  val prisonerNumber: String,
  val pncNumber: String? = null,
  val pncNumberCanonicalShort: String? = null,
  val pncNumberCanonicalLong: String? = null,
  val croNumber: String? = null,
  val bookingId: String? = null,
  val bookNumber: String? = null,
  val title: String? = null,
  @Schema(required = true, description = "First Name", example = "Robert")
  val firstName: String,
  val middleNames: String? = null,
  @Schema(required = true, description = "Last name", example = "Larsen")
  val lastName: String,
  @Schema(required = true, description = "Date of Birth", example = "1975-04-02")
  val dateOfBirth: LocalDate,
  val gender: String? = null,
  val ethnicity: String? = null,
  val raceCode: String? = null,
  val youthOffender: Boolean? = false,
  val maritalStatus: String? = null,
  val religion: String? = null,
  val nationality: String? = null,
  val status: String? = null,
  val lastMovementTypeCode: String? = null,
  val lastMovementReasonCode: String? = null,
  val inOutStatus: String? = null,
  @Schema(description = "Prison ID", example = "MDI")
  val prisonId: String?,
  val lastPrisonId: String? = null,
  @Schema(description = "Prison Name", example = "HMP Leeds")
  val prisonName: String?,
  @Schema(description = "In prison cell location", example = "A-1-002")
  val cellLocation: String? = null,
  val aliases: List<Alias>? = null,
  val alerts: List<Alert>? = null,
  val csra: String? = null,
  val category: String? = null,
  val legalStatus: String? = null,
  val imprisonmentStatus: String? = null,
  val imprisonmentStatusDescription: String? = null,
  @Schema(description = "Convicted Status", example = "Convicted", allowableValues = ["Convicted", "Remand"])
  val convictedStatus: String? = null,
  val mostSeriousOffence: String? = null,
  val recall: Boolean? = false,
  val indeterminateSentence: Boolean? = false,
  val sentenceStartDate: String? = null,
  val releaseDate: String? = null,
  val confirmedReleaseDate: String? = null,
  val sentenceExpiryDate: String? = null,
  val licenceExpiryDate: String? = null,
  val homeDetentionCurfewEligibilityDate: String? = null,
  val homeDetentionCurfewActualDate: String? = null,
  val homeDetentionCurfewEndDate: String? = null,
  val topupSupervisionStartDate: String? = null,
  val topupSupervisionExpiryDate: String? = null,
  val additionalDaysAwarded: Long? = null,
  val nonDtoReleaseDate: String? = null,
  val nonDtoReleaseDateType: String? = null,
  val receptionDate: String? = null,
  val paroleEligibilityDate: String? = null,
  val automaticReleaseDate: String? = null,
  val postRecallReleaseDate: String? = null,
  val conditionalReleaseDate: String? = null,
  val actualParoleDate: String? = null,
  val tariffDate: String? = null,
  val releaseOnTemporaryLicenceDate: String? = null,
  @Schema(description = "current prison or outside with last movement information.", example = "Outside - released from Leeds")
  val locationDescription: String? = null,
  val restrictedPatient: Boolean? = false,
  val supportingPrisonId: String? = null,
  val dischargedHospitalId: String? = null,
  val dischargedHospitalDescription: String? = null,
  val dischargeDate: String? = null,
  val dischargeDetails: String? = null,
  @Schema(description = "Incentive level")
  val currentIncentive: CurrentIncentive? = null,
  val heightCentimetres: Long? = null,
  val weightKilograms: Long? = null,
  val hairColour: String? = null,
  val rightEyeColour: String? = null,
  val leftEyeColour: String? = null,
  val facialHair: String? = null,
  val shapeOfFace: String? = null,
  val build: String? = null,
  val shoeSize: Long? = null,
  val tattoos: List<Tattoo>? = null,
  val scars: List<Scar>? = null,
  val marks: List<Mark>? = null,
  val addresses: List<Address>? = null,
  val emailAddresses: List<EmailAddress>? = null,
  val phoneNumbers: List<PhoneNumber2>? = null,
  val identifiers: List<Identifier>? = null,
  val allConvictedOffences: List<AllConvictedOffence>? = null,
)
